name: Docker image rebuild
env: 
  AWS_REGION_NAME           : "eu-central-1a"

on:
  push:
    branches: [ master ]

jobs: 
  ci_part:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Copy repository to src
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.MY_AWS_HOSTNAME }}
        username: ${{ secrets.MY_AWS_USERNAME }}
        key: ${{ secrets.MY_AWS_ACCESS_KEY }}
        script: |
          cd /home/ubuntu/project/temp ; git clone git@github.com:gokunull/docker-container.git
          ls -la
      
