name: Docker image rebuild
env: 
  AWS_REGION_NAME           : "eu-central-1a"

on:
  push:
    branches: [ master ]

jobs: 
  ci_part:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Copy repository to src
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.MY_AWS_HOSTNAME }}
        username: ${{ secrets.MY_AWS_USERNAME }}
        key: ${{ secrets.MY_AWS_ACCESS_KEY }}
        script: |
          sudo rm -rf /home/ubuntu/project/temp/*; sudo rm -rf /home/ubuntu/project/src/*
          cd /home/ubuntu/project/temp ; git clone git@github.com:gokunull/docker-container.git
          mv /home/ubuntu/project/temp/docker-container/* /home/ubuntu/project/src
          docker stop static-page && docker rm $_   
          docker run --restart=always -dit --name static-page -p 172.31.28.116:80:80 -v /home/ubuntu/project/src/:/usr/local/apache2/htdocs/ httpd:2.4
